<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UniteCorp.SharedKernel\UniteCorp.SharedKernel.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Features\GeocercaActividad\**\*.cs" />
    <Compile Include="..\Features\PuntoControl\**\*.cs" />
    <Compile Include="..\Features\DispositivoVerificador\**\*.cs" />
    <Compile Include="..\Features\AsistenciaFisica\**\*.cs" />
  </ItemGroup>

</Project>